apiVersion: v1
kind: Service
metadata:
  name: dominio-app-service
spec:
  selector:
    app: dominio-app  # Conecta-se ao pod do backend
  ports:
    - protocol: TCP
      port: 3000  # Porta que será exposta externamente
      targetPort: 3000  # Porta do container
  type: LoadBalancer  # Expor a aplicação externamente através de um LoadBalancer
